name: Release
on:
  push:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: './infinitest/'
      - uses: actions/checkout@v2
        with:
          repository: 'infinitest/infinitest.github.com' 
          path: './website/'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Decode keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 --decode > ./infinitest/keystore.jks
      - name: apt-get update
        run: sudo apt-get update
      - name: Install SWT dependencies
      # Eclipse/SWT 3.6 requires GTK+ 2.4.1 and its dependencies
        run: sudo apt-get install -y gtk2.0 libxtst6
      - name: Build and Test
      # We need a virtual X11 for the Eclipse unit tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            mvn -B install -P release \
              -Dkeystore-password=${{ secrets.KEYSTORE_PASSWORD }}
      - name: Copy the Eclipse plugin to the website
        run: cp -r ./infinitest/infinitest-eclipse/target/update_site/* ./website
      - name: Commit website changes
        uses: EndBug/add-and-commit@v9
        with:
          message: release ${{ github.event.release.tag_name }}
          cwd: './website/'
